### PR TITLE
Update tool-Docker-action to v2.1.0

### PR DESCRIPTION
**Pull request by nwiltsie**
This PR updates the `tool-Docker-action` Action to version 2.1.0. There are a few big changes in this version:

1. Pushing to any branch `foo` will [build this repository's image](https://github.com/uclahs-cds/tool-Docker-action/pull/14) and tag it as `branch-foo`. That tagged image will be removed when the branch is deleted.
1. By default the Action will only build [SemVer](https://semver.org/) tags (e.g. `v1.2.3-xxx`). Repositories that need to use other kinds of tags (e.g. `v1.2beta`) can pass the optional `non-semver-tags` argument; doing so will build all tags that begin with `v`.

There are a bunch of smaller changes buried in there - you can see them all at [this link](https://github.com/uclahs-cds/tool-Docker-action/compare/ebe9f1c...v2.1.0).

Based on this repository's existing tags, I've determined that it _does_ follow semantic versioning. The updated workflow therefore does _not_ pass the `non-semver-tags` argument to the Action, although it can be uncommented in the future if need be.

### CODE REVIEW

**Comment by nwiltsie** [comment]
Hmm, something's wonky here. The image isn't building correctly and I don't think it's related to my changes. @dan-knight can you review the [build logs](https://github.com/uclahs-cds/docker-BoutrosLabPlottingGeneral/actions/runs/10410182685/job/28831417151?pr=9) and see if you can figure out the problem?

**Comment by dan-knight** [comment]
Weird. The error message isn't super informative, at least to me. @Faizal-Eeman created this image, so I wonder if he knows more about that line.

**Comment by Faizal-Eeman** [comment]
> Hmm, something's wonky here. The image isn't building correctly and I don't think it's related to my changes. @dan-knight can you review the [build logs](https://github.com/uclahs-cds/docker-BoutrosLabPlottingGeneral/actions/runs/10410182685/job/28831417151?pr=9) and see if you can figure out the problem?

Created an issue to look into this. https://github.com/uclahs-cds/docker-BoutrosLabPlottingGeneral/issues/10#issue-2470887997

**Comment by nwiltsie** [comment]
@Faizal-Eeman confirmed that the build issue is unrelated to this change, so I'm going to go ahead and merge this. That will make it _much_ easier to fix, as any new PRs will try to build the image!

**Review by Faizal-Eeman — APPROVED** [review]
Updates in the PR are independent of the CICD error.

This PR can be merged.

**Pull request merged**
